version: '3'

services:
  jira:
    build: ./jira-5.0.4
    image: jira:5.0.4
    container_name: jira
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '8080:8080'
    environment:
      - 'JIRA_DATABASE_URL=mysql://jira@mysql/jiradb'
      - 'JIRA_DB_PASSWORD=jira'
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
    labels:
      com.blacklabelops.description: "Atlassian Jira"
      com.blacklabelops.service: "jira"
    networks:
      - default
      - aladdin_default
    external_links:
      - mysql

volumes:
  jiradata:
    external: false

networks:
  aladdin_default:
    external: true
